### PR TITLE
Allow creation of services which don't require Bluetooth connection

### PR DESCRIPTION
**Pull request by strangepleasures**
Bluetooth is required by default, it means that device services stop when it's off.
That can be changed by overriding `isBluetoothConnectionRequired`.
A better solution would be not to require Bluetooth by default and to have a separate class encapsulating Bluetooth-related behaviour:
```java
public abstract class BluetoothDeviceService extends DeviceService  {
```
but that would be a breaking API change.

### CODE REVIEW

**Comment by blootsvoets** [comment]
In the `split_login_manager`, the bluetooth listener only activates if there is a BLUETOOTH permission requested. Would that also resolve your issue?

**Comment by strangepleasures** [comment]
Yes and no. We have at least one exception, namely PhoneBluetoothManager. It requires BLUETOOTH permission but should be able to work even when Bluetooth is off.

**Comment by blootsvoets** [comment]
Good point.

**Comment by blootsvoets** [comment]
@strangepleasures would this merge solve both issues?

**Pull request merged**
