### PR TITLE
Added Logout Functionality to the Application

### LINKED ISSUE #457: Implement Logout Functionality to Facilitate Patient Switching
### Description

To address the need for using the app in clinic or hospital environments where the same device and app instance are used with multiple patients, we propose implementing a logout functionality. This will allow clinicians to log out from the app and redirect them to the login screen, enabling a seamless transition between patients. 

 **Redirect to Login**:
 After logging out, the user should be redirected to the login screen, allowing them to scan a new QR code for a different patient.

### PR DESCRIPTION
**Pull request by this-Aditya**
### Added Logout Functionality to the Application

- Implemented the feature to allow users to log out from the application.

- Verified there are no memory leaks during the logout process, as demonstrated in the heap dump screenshot:

Heap Dump Verification]

### CODE REVIEW

**Comment by this-Aditya** [comment]
- Attached is a video showcasing the logout functionality in action:
  [Video Playback of Logout Functionality](https://github.com/user-attachments/assets/db55622c-83f5-477c-9406-1363bffc2ebb
)

**Comment by this-Aditya** [comment]
However, I am getting some warnings when logging out:

> 2024-07-27 22:29:45.192 11196-11196 ActivityThread          org.radarcns.detail                  E  Service org.radarbase.monitor.application.ApplicationStatusService has leaked IntentReceiver org.radarbase.android.util.OfflineProcessor$3@604f1d that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                                                    android.app.IntentReceiverLeaked: Service org.radarbase.monitor.application.ApplicationStatusService has leaked IntentReceiver org.radarbase.android.util.OfflineProcessor$3@604f1d that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                                                    	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1980)
                                                                                                    	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1690)
                                                                                                    	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1901)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1853)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1841)
                                                                                                    	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:772)
                                                                                                    	at org.radarbase.android.util.OfflineProcessor$start$2.invoke(OfflineProcessor.kt:106)
                                                                                                    	at org.radarbase.android.util.OfflineProcessor$start$2.invoke(OfflineProcessor.kt:104)
                                                                                                    	at org.radarbase.android.util.SafeHandler$Companion.tryRunOrNull(SafeHandler.kt:298)
                                                                                                    	at org.radarbase.android.util.SafeHandler$Companion.access$tryRunOrNull(SafeHandler.kt:273)
                                                                                                    	at org.radarbase.android.util.SafeHandler.execute$lambda$2$lambda$1(SafeHandler.kt:158)
                                                                                                    	at org.radarbase.android.util.SafeHandler.$r8$lambda$6MOLh21o2LLm17MOwJtRamInMiA(SafeHandler.kt:0)


and 

> 2024-07-27 22:29:45.200 11196-11196 ActivityThread          org.radarcns.detail                  E  Service org.radarcns.detail.RadarServiceImpl has leaked IntentReceiver org.radarbase.android.util.BatteryLevelReceiver$receiver$1@a8bfeef that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                                                    android.app.IntentReceiverLeaked: Service org.radarcns.detail.RadarServiceImpl has leaked IntentReceiver org.radarbase.android.util.BatteryLevelReceiver$receiver$1@a8bfeef that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                                                    	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1980)
                                                                                                    	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1690)
                                                                                                    	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1901)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1853)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1841)
                                                                                                    	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:772)
                                                                                                    	at org.radarbase.android.util.BatteryLevelReceiver.register(BatteryLevelReceiver.kt:54)
                                                                                                    	at org.radarbase.android.util.BatteryStageReceiver.register(BatteryStageReceiver.kt:36)
                                                                                                    	at org.radarbase.android.data.TableDataHandler.doEnableSubmitter(TableDataHandler.kt:227)
                                                                                                    	at org.radarbase.android.data.TableDataHandler.access$doEnableSubmitter(TableDataHandler.kt:47)
                                                                                                    	at org.radarbase.android.data.TableDataHandler$enableSubmitter$1.invoke(TableDataHandler.kt:218)
                                                                                                    	at org.radarbase.android.data.TableDataHandler$enableSubmitter$1.invoke(TableDataHandler.kt:216)
                                                                                                    	at org.radarbase.android.util.SafeHandler$Companion.tryRunOrNull(SafeHandler.kt:298)
                                                                                                    	at org.radarbase.android.util.SafeHandler$Companion.access$tryRunOrNull(SafeHandler.kt:273)
                                                                                                    	at org.radarbase.android.util.SafeHandler.executeReentrant(SafeHandler.kt:115)
                                                                                                    	at org.radarbase.android.data.TableDataHandler.enableSubmitter(TableDataHandler.kt:216)
                                                                                                    	at org.radarbase.android.data.TableDataHandler.access$enableSubmitter(TableDataHandler.kt:47)
                                                                                                    	at org.radarbase.android.data.TableDataHandler$handler$1.invoke(TableDataHandler.kt:329)
                                                                                                    	at org.radarbase.android.data.TableDataHandler$handler$1.invoke(TableDataHandler.kt:318)
                                                                                                    	at org.radarbase.android.util.SafeHandler$Companion.tryRunOrNull(SafeHandler.kt:298)

I tried to get rid of them but was not able to. They are not causing any change in functionality. Any support on how to remove these warnings would be appreciated.

**Comment by this-Aditya** [comment]
I think the CI is failing due to the Polar plugin package.

**Comment by yatharthranjan** [comment]
> I think the CI is failing due to the Polar plugin package.

Yes please rebase with dev as polar has been commented out now

**Comment by this-Aditya** [comment]
Closing this as it conflicts with the `ktor-coroutines` branch. The logout feature will be added to [this PR.](https://github.com/RADAR-base/radar-commons-android/pull/442)

**Comment by this-Aditya** [comment]
Closing this as it conflicts with the ktor-coroutines branch. The logout feature will be added to [this pr.](https://github.com/RADAR-base/radar-commons-android/pull/442)

**Pull request closed without merging**
